name: dexcom_share_api
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  dio: ^4.0.6
  freezed_annotation: ^2.2.0

dev_dependencies:
  freezed: ^2.1.1
  json_serializable: ^6.5.1
  lint: ^1.10.0
